$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command  # This is correct for trial definitions
name: train_model
display_name: train_model
inputs: 
  train_data:
    type: uri_folder
outputs:
  model_output:
    type: mlflow_model
command: >-
  python train.py 
  --train_data ${{inputs.train_data}}
  --model_output ${{outputs.model_output}}
environment: azureml:pima-train-env@latest
