$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

train_model:
    name: train_model
    display_name: train-model
    code: ../../../data-science/src
    command: >-
      python train.py 
      --train_data ${{inputs.train_data}} 
      --model_output ${{outputs.model_output}}
    environment: azureml:pima-train-env@latest
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
    outputs:
      model_output: ${{parent.outputs.trained_model}}
